version: '3.8'

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq3"
    hostname: "imageformatter"
    restart: "no"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    labels:
      NAME: "rabbitmq1"
    ports:
      - "5672:5672"
      - "15672:15672"